name: manual-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: false
        default: dev
        type: string
      version:
        description: Version
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
